pro/urls.py
from django.urls import path
from . import views

app_name='pro'

urlpatterns = [ 
   #/music/
  
   path('', views.IndexView.as_view(),name='index'),

   path('task/', views.TaskDisplay.as_view(),name='task'),

   
   #/music/<album.id>/
   path('<int:pk>/',views.DetailView.as_view(),name='detail'),

   #/music/album/add/
   path('task/add/', views.TaskCreate.as_view(),name='add-task'),

   path('team/add/', views.TeamCreate.as_view(),name='add-team'),

   path('mem/add/', views.TeamMem.as_view(),name='add-mem'),

   path('comment/', views.comment_view, name='add-comment'),

   path('edit/<int:pk>/', views.TaskUpdate.as_view(),name='task-update'),

]

pro/models.py
from django.db import models
from django.urls import reverse
from django import forms


class Team(models.Model):
	team_creator = models.CharField(max_length=250)
	team_name = models.CharField(max_length=250)

	def __str__(self):
		return self.team_name + ' - ' + self.team_creator

	def get_absolute_url(self):
		return reverse('pro:index')

class Comment(models.Model):
	username = models.CharField(max_length=250)
	comment = models.CharField(max_length=500)

class Team_mem(models.Model):
	team = models.ForeignKey(Team, on_delete=models.CASCADE)
	mem = models.CharField(max_length=250)

	def __str__(self):
		return self.mem 

	def get_absolute_url(self):
		return reverse('pro:index')
 	

class Task(models.Model):
	team = models.ForeignKey(Team, on_delete=models.CASCADE)	
	title = models.CharField(max_length=250)
	description = models.CharField(max_length=500)
	assignee = models.CharField(max_length=250)
	status = models.CharField(max_length=250,default='planned')
	task_creator = models.CharField(max_length=250)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('pro:index')		
	

	

pro/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.Form):

	username = forms.CharField(max_length=250)
	comment = forms.CharField(widget=forms.Textarea)

	class Meta:
		model = Comment
		fields = ['username','comment'] 

pro/views.py
from django.shortcuts import render, redirect
from .models import Team, Task, Team_mem
from django.views import generic
from django.http import HttpResponse, Http404
from django.contrib.sessions.backends.db import SessionStore
from .forms import CommentForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'pro/index.html'
	context_object_name = 'all_teams'


	def get_queryset(self):
		return Team.objects.all()

class DetailView(generic.DetailView):
	model = Team
	template_name = 'pro/details.html'

class TaskDisplay(generic.ListView):
	model = Task , Team_mem
	template_name = 'pro/tasks.html'

	def get_queryset(self):
		user = self.request.session['un']
		a = Team_mem.objects.get(mem=user).team
		return Task.objects.filter(team=a)



class TaskCreate(CreateView):
	model = Task
	fields = ['title','description', 'assignee','team']
	template_name = 'pro/create_form.html'
	

class TaskUpdate(UpdateView):
	model = Task
	fields = ['title','description', 'assignee','status']
	template_name = 'pro/create_form.html'

	def __str__(self, request,no):
		user = self.request.session['un']
		a = Task.objects.get(pk=no).task_creator
		if not user == a:
			raiseHttp404("You cannot Edit")


class TeamCreate(CreateView):
	
	model = Team
	fields = ['team_creator','team_name']
	template_name = 'pro/create_form.html'

	def __str__(self):
		return redirect('index')


class TeamMem(CreateView):
	
	model = Team_mem
	fields = ['team', 'mem']
	template_name = 'pro/create_form.html'	


def comment_view(request):
	if request.method == 'POST':
		form = CommentForm(request.POST or None)
		if form.is_valid():
			cmt = form.save(commit=False)
			comment = form.cleaned_data.get('comment')
			cmt.set_comment(comment)
			cmt.save()
			return redirect('pro:task')
	else:
		form = CommentForm()
	template = 'pro/addcomment.html'
	context = {'form': form}
	return render(request, template, context)
	













pro/templates/pro/addcomment.html
{% extends 'pro/base.html' %}

{% block body%}

	{% for cmt in object_list %}
		{{cmt.username}}<br>
		{{cmt.comment}}

	{% endfor %}

	<h1>Add New Comment</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p}}
		<button tye='submit'>Submit</button>
	</form>
{% endblock %}	

pro/templates/pro/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>T.T</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'pro/style.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">

			<!--Header-->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					
				</button>
				<a class="navbar-brand" href="{% url 'pro:index' %}">Home</a>
			</div>

			<!--Item-->
			<div class="collapse navbar-collapse" id="tapNavBar">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="{% url 'pro:index' %}" >
							Teams
						</a>
					</li>
					<li class="">
						<a href = "task/{{team.id}}" >
							Tasks
						</a>
					</li>


				</ul>

			
			
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<a href="#" >
							<span class=glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Hi!@{{ request.session.un }}
						</a>
						
					</li>
					<li class="">
						<a href="{% url 'pro:add-team'%}" >
							<span class=glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Create Team
						</a>
					</li>
					<li class="">
						<a href="{% url 'pro:add-mem'%}" >
							<span class=glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add menbers
						</a>
					</li>
					<li class="">
						<a href="{% url 'pro:add-task'%}" >
							<span class=glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Create Task
						</a>
					</li>
					<li class="">
						<a href="{% url 'logout' %}" >
							<span class=glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
						</a>
					</li>

				</ul>

		</div>
	</nav>
	{% block body%}
	{% endblock %}

</body>
</html>

pro/templates/pro/create_form.html
{% extends 'pro/base.html' %}

{% block body%}
<div class="container-fluid">

	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data" >
						{% csrf_token%}
						{% include 'pro/form-template.html'%}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="Submit" class="btn btn-success">Submit</button>
							</div>
						</div>

						

					</form>	
				</div>
			</div>
		</div>
	</div>	
</div>	
{% endblock %}			

pro/templates/pro/details.html

{% extends 'pro/base.html' %}

{% block body%}

	
{{team}}



{% endblock %}

pro/templates/pro/form-template.html
{% for field in form%}
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
    		<span class="text-danger small">{{ field.errors }}</span>
    	</div>
    	<label class="control-label col-sm-2">{{ field.label_tag }}</label>
    	<div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}    

pro/templates/pro/index.html

{% extends 'pro/base.html' %}

{% block body%}


{% if all_teams %}
	<ul>
		{% for team in all_teams %}
		<li> <a href = "{{team.id}}">
			<big>
		{{team.team_name}}</big></a></li>

		{% endfor %}

	</ul>


	
	
{% else %}
	<h3> You Dont have any team</h3>
{% endif %}			


{% endblock %}

pro/templates/pro/tasks.html
{% extends 'pro/base.html' %}

{% block body%}
<h1>Tasks are:</h1>
<div class="container">


	<table border="0"  width="100%" >
		<tr>
			<th><center><u> Title</u>  </center> </th>
			<th><center><u>Description</u></center></th>
			<th><center><u>Assignee </u></center></th>
			<th><center><u>Status</u></center> </th>
			<th> </th>
			<th></th>
		</tr>
		{% for task in object_list %}
		<tr>
			<td><center><br>{{ task.title }}</center></td>
			<td><center><br>{{ task.description }}</center></td>
			<td><center><br>{{ task.assignee }}</center></td>
			<td><center><br>{{ task.status }}</center></td>
			<td><center><br><a href="{% url 'pro:task-update' task.id %}">Edit</a></center></td>
			<td><center><br><a href="{% url 'pro:add-comment' %}">Comment</a></center></td>
			
		</tr>
		
		
		
		
		
		{% endfor %}
	</table>	

		



	
		




		

{% endblock %}